#!/bin/bash

# This bash script is used to setup docker environment in CentOS
# @author Harrison Feng <harrison.feng@gmail.com>


# Color Definition
TXTRESET='\e[0m'
TXTRED='\e[0;31m'
TXTGREEN='\e[0;32m'
TXTBLUE='\e[0;34m'
TXTPURPLE='\e[0;35m'


BTXTRED='\e[1;31m'
BTXTGREEN='\e[1;32m'
BTXTBLUE='\e[1;34m'

ERROR_CODE=2 # Invalid parameters

VERSION=$1


function usage(){
    if [ -z "$VERSION" ]; then
        echo -e "$TXTRED
        ##############################################
        Please give me the docker version (e.g. 1.9.1)

        Usage: $0 1.9.1

        Here are versions available:
        1.7.0
        1.7.1
        1.8.0
        1.8.1
        1.8.2
        1.8.3
        1.9.0
        1.9.1
        1.10.0
        1.10.1
        1.10.2
        1.10.3
        1.11.0
        1.11.1
        ##############################################
        $TXTRESET"
        exit $ERROR_CODE
    fi
}


function prepare_repo() {
    if [ ! -f /etc/yum.repos.d/docker.repo ]; then
        \cp -f docker.repo /etc/yum.repos.d/
    fi
}


function install() {
    yum install -y docker-engine-$VERSION
}


usage
prepare_repo
install


if [ -f /usr/bin/docker ]; then
    service docker start
fi
