#!/bin/bash

# Docker Setup¬
#¬
# Copyright (C) 2016 Harrison Feng <feng.harrison@gmail.com>¬
#¬
# This program is free software: you can redistribute it and/or modify¬
# it under the terms of the GNU General Public License as published by¬
# the Free Software Foundation, either version 3 of the License, or¬
# (at your option) any later version.¬
#¬
# This program is distributed in the hope that it will be useful,¬
# but WITHOUT ANY WARRANTY; without even the implied warranty of¬
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the¬
# GNU General Public License for more details.¬
#¬
# You should have received a copy of the GNU General Public License¬
# along with this program. If not, see [http://www.gnu.org/licenses/].¬
#¬
# Docker Setup is a project which enable docker environment easily in your¬
# linux box.¬
#¬
# @author Harrison Feng <feng.harrison@gmail.com>¬
# @file nsdocker.sh¬

# Color Definition¬
TXTRESET='\e[0m'
TXTRED='\e[0;31m'
TXTGREEN='\e[0;32m'
TXTBLUE='\e[0;34m'
TXTPURPLE='\e[0;35m'

BTXTRED='\e[1;31m'
BTXTGREEN='\e[1;32m'
BTXTBLUE='\e[1;34m'

# Error code
invalid_container=1
nsenter_not_exists=2


usage() { 
    echo -e "$TXTGREEN

    Usage: $(basename $0) CONTAINER [COMMAND [ARG]...]

    Enter docker CONTAINER and executes the specified COMMAND.
    If COMMAND is not specified, runs an interactive shell in CONTAINER.

    $TXTRESET"
}

command_exists() { command -v "$@" > /dev/null 2>&1; }

nsdocker() {
    if command_exists nsenter; then
        if [ ! -z "$1" ]; then
            pid=$(docker inspect -f "{{.State.Pid}}" "$1")
            if [ -z "$pid" ]; then
                exit $invalid_container
            fi
            shift
            opts="--target $pid --mount --uts --ipc --net --pid --"
            if [ -z "$1" ]; then
                nsenter $opts su - root
            else
                nsenter $opts env --ignore-environment -- "$@"
            fi
        else
            usage
            exit 1
        fi
    else
        echo -e "$TXTRED\nnsenter is NOT installed or NOT in your PATH.$TXTRESET"
        exit $nsenter_not_exists
    fi
}

nsdocker $@
